[tool.ruff]
# Exclude backup files and other non-essential files
exclude = [
    ".git",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    "*.egg-info",
]

# Set line length to 120 characters
line-length = 120

[tool.ruff.lint]
# Enable specific rule categories
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "UP", # pyupgrade
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
]

# Ignore specific rules that might be too strict for this project
ignore = [
    "E501",  # line too long (handled by line-length setting)
    "B008",  # do not perform function calls in argument defaults
]

[tool.ruff.lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]
# Allow longer lines in test files
"tests/**/*.py" = ["E501"]

[tool.ruff.lint.isort]
# Configure import sorting
known-first-party = ["app_logger", "cookie_manager", "download_threads", "gui"]
force-single-line = false
lines-after-imports = 2