name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest

      - name: Run tests with coverage (pytest)
        run: |
          python -m coverage run -m pytest -ra

      - name: Coverage report
        run: |
          python -m coverage report -m
          python -m coverage xml -o coverage.xml
          python -m coverage html -d htmlcov

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
